name: Release

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - '*.json'
    branches:
      - master

jobs:
  release:
    name: 'Release'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false # <--- this

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
        git commit --allow-empty -m "fix(test): semantic release"

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
