name: Release

on:
  workflow_dispatch:
  push:
#    paths:
#      - 'src/**'
#      - '*.json'
    branches:
      - master

jobs:
  release:
    name: 'Release'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false # <--- this

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install semantic-release
        run: |
          npm install -g semantic-release @semantic-release/git conventional-changelog-conventionalcommits

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
