name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: 'Release'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get version from package.json before release step
        id: initversion
        run: echo "::set-output name=version::$(node -p -e "require(\"./package.json\").version")"


      - name: Bump version
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: diamond-bot
          GIT_AUTHOR_EMAIL: diamond-bot@diamondlord.dev
          GIT_COMMITTER_NAME: diamond-bot
          GIT_COMMITTER_EMAIL: diamond-bot@diamondlord.dev
        run: npm version patch

      - name: Get version from package.json after release step
        id: extractver
        run: echo "::set-output name=version::$(node -p -e "require(\"./package.json\").version")"

      - name: Create Release
        if: steps.initversion.outputs.version != steps.extractver.outputs.version
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extractver.outputs.version }}
          release_name: Release ${{ steps.extractver.outputs.version }}
          draft: false
          prerelease: false

#      - name: Upload Release Asset
#        id: upload-release-asset
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
#          asset_path: ./my-artifact.zip
#          asset_name: my-artifact.zip
#          asset_content_type: application/zip

      - name: Create Pull Request with updated package files
        if: steps.initversion.outputs.version != steps.extractver.outputs.version
        uses: Diamondlord/create-pull-request@v2.4.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(release): ${{ steps.extractver.outputs.version }}'
          committer: diamond-bot <diamond-bot@diamondlord.dev>
          author: diamond-bot <diamond-bot@diamondlord.dev>
          title: 'chore(release): ${{ steps.extractver.outputs.version }}'
          body: 'Version bump in package.json and package-lock.json for release [${{ steps.extractver.outputs.version }}](https://github.com/${{github.repository}}/releases/tag/v${{ steps.extractver.outputs.version }})'
          branch: version-bump/${{ steps.extractver.outputs.version }}
